### ISSUE TITLE
demo app is incompatible

### ISSUE THREAD

**Issue by prashantwosti** [ppamorim/Dragger#10]
I have a Nexus7 and a Nexus 4 both running lollipop (5.0.2) and your demo app is incompatible. I wanted to check out the sample app before trying this library.

**Comment by leonardoxh** [comment]
Have you tried the demo on playstore ? 

Here on my Nexus 5 (Android 5.1) it works like a charm.

**Comment by prashantwosti** [comment]
yes.. i tried to installed from Google play. but it says my phone(Nexus 4)
is incompatible.
- sent via Nexus 4

**Comment by ppamorim** [comment]
@prashantwosti I've updated the version of the app on Play Store, please, review it!

**Comment by prashantwosti** [comment]
now it works.

thanks.
- sent via Nexus 4
