### ISSUE TITLE
Problems with Jitpack Dependency

### ISSUE THREAD

**Issue by LuizGadao** [ppamorim/Dragger#16]
When I add dependecie Jitpack I get this error in Android Studio.

Error:A problem occurred configuring project ':app'.

> Artifact 'appcompat-v7.jar (com.android.support:appcompat-v7:22.1.0)' not found.
>   Searched in the following locations:
>       https://jitpack.io/com/android/support/appcompat-v7/22.1.0/appcompat-v7-22.1.0.jar

**Comment by ppamorim** [comment]
Can you show your complete build.gradle?

**Comment by LuizGadao** [comment]
![captura de tela 2015-04-29 as 10 02 45](https://cloud.githubusercontent.com/assets/3384999/7391363/f2e25ff4-ee56-11e4-891d-87f7feb876f7.png)

**Comment by ppamorim** [comment]
Try to add on the build.gradle inside the "app" project.

**Comment by LuizGadao** [comment]
It's happing the same error.

**Comment by ppamorim** [comment]
try to use:
     compile 'com.github.ppamorim:recyclerrenderers:v1.15.1'

**Comment by LuizGadao** [comment]
No success.
![captura de tela 2015-04-29 as 15 22 01](https://cloud.githubusercontent.com/assets/3384999/7398175/ae80af28-ee83-11e4-83e2-8c7e5158b8db.png)

**Comment by ppamorim** [comment]
Well, I've found the problem. Wait a moment.

**Comment by ppamorim** [comment]
Can you try to add this?

```
compile 'com.github.ppamorim:dragger:v1.0.2'
```

Sorry for the RecyclerRenderers. Nadaver. :p

**Comment by LuizGadao** [comment]
Still not working,

**Comment by ppamorim** [comment]
It's working for me.
Remember, remove the RecyclerRenderers code and clear your project.

**Comment by LuizGadao** [comment]
For me it still not working.
Can you paste your build.gradle to me?

**Comment by ppamorim** [comment]
You MUST need use the compileSdkVersion >= 22 and buildToolsVersion >= "22.1.1"
Check this:
https://github.com/ppamorim/Amazing-MVP/blob/master/amazingMVP/build.gradle

**Comment by leonardoxh** [comment]
I think this problem is related to your app compat dependencies (or Jitpack at all), historicaly, the SDK Manager is a shit.

So, change the <code>compileSdkVersion</code> and <code>buildToolsVersion</code> like @ppamorim comment, and change your appcompat version to <code>com.android.support:appcompat-v7:22.1.1</code>

Also, make sure you have downloded the latest app compat library on SDK Manager

Let me know if this works.

**Comment by leonardoxh** [comment]
If any think like this not work, I'll change the library and publish this lib on maven central to make sure that dependencies is correct compiled.

**Comment by LuizGadao** [comment]
It's work.

Thank you.

**Comment by leonardoxh** [comment]
Yeah, :+1:
