### ISSUE TITLE
The activity by value

### ISSUE THREAD

**Issue by guoyoujin** [ppamorim/Dragger#23]
When the activity left sliding finish (), how to forward an activity by value

**Comment by ppamorim** [comment]
@guoyoujin  I can't understand your problem. Can you detail it?

**Comment by guoyoujin** [comment]
When I rewrite
Your onActivityResult (int requestCode, int the resultCode, Intent data) method,
Use this. StartActivityForResult (new Intent (Mainactivity. This, TestActivity. Class), 0) start the TestActivity, I use the TestActivity end of the slide, to the right and I want to pass a value of TestActivity to Mainactivity, this how to pass the value

**Comment by ppamorim** [comment]
Use a intent.
