### ISSUE TITLE
setDraggerLimit(float limit)

### ISSUE THREAD

**Issue by silviahisham** [ppamorim/Dragger#35]
What do setDraggerLimit(limit) do exactly? and Please doc the code when possible.

**Comment by ppamorim** [comment]
This method will determine the max draggable position to auto collapse the DraggerView. I need to comment the code and add this method to doc. Stay alert.

**Comment by silviahisham** [comment]
and what's the default value?

**Comment by ppamorim** [comment]
@silviahisham 0.5, the center of screen.

**Comment by silviahisham** [comment]
@ppamorim  Thank you
