### ISSUE TITLE
Conflict with view pager

### ISSUE THREAD

**Issue by silviahisham** [ppamorim/Dragger#38]
I set dragger position to `DraggerPosition.TOP` inside my activity which also has a view pager, swiping the view pager left and right conflicts with the sliding effect of the dragger, which makes it very hard to swipe the pages of the view pager.

**Comment by ppamorim** [comment]
@silviahisham Use the method `draggerView.setSlideEnabled(bool)` to enable or disable the drag. You must add a touch listener on your ViewPager to handle the slide.
