### ISSUE TITLE
Error:Could not find com.github.ppamorim:dragger:1.2.

### ISSUE THREAD

**Issue by zeshaoaaa** [ppamorim/Dragger#49]
Below code is repositories of my build.gradle(project)

repositories {
        maven { url "https://jitpack.io" }
        mavenCentral()
        jcenter()
        maven { url 'http://ksoap2-android.googlecode.com/svn/m2-repo' } // <-- added for ksoap
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }

**Comment by mozi22** [comment]
did you solve this ?

**Comment by zeshaoaaa** [comment]
@mozi22  I solved it. But I forget the solution, sorry. Then I meeting next issue is when my activity dragging, the activity have a white background. But the activity background is @null.

**Comment by Grohden** [comment]
2 years late, but you should put maven central (and probably others) above the urls.

```
mavenCentral()
jcenter()
maven { url "https://jitpack.io" }
maven { url 'http://ksoap2-android.googlecode.com/svn/m2-repo' } // <-- added for ksoap
maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
```

**Comment by zeshaoaaa** [comment]
@Grohden Thanks for your help. I'm closing this issue.
